### ISSUE TITLE
Unable to view badpenny job log in production

### ISSUE THREAD

**Issue by Callek** [mozilla/build-relengapi#207]
Current production is 1.1, and I'm unable to view a badpenny job log (interestingly there is no job on staging)
```
Traceback (most recent call last):
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request rv = self.dispatch_request()
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args)
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/newrelic-2.46.0.37/newrelic/hooks/framework_flask.py", line 40, in _nr_wrapper_handler_ return wrapped(*args, **kwargs)
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/relengapi/lib/api.py", line 103, in replacement result = wrapped(*args, **kwargs)
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/relengapi/lib/permissions.py", line 85, in req return wrapped(*args, **kwargs)
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/relengapi/blueprints/badpenny/__init__.py", line 92, in get_job_logs tables.BadpennyJobLog.id == job_id).first()
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2333, in first ret = list(self[0:1])
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2200, in __getitem__ return list(res)
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2404, in __iter__ return self._execute_and_instances(context)
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2419, in _execute_and_instances result = conn.execute(querycontext.statement, self._params)
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 720, in execute return meth(self, multiparams, params)
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 317, in _execute_on_connection return connection._execute_clauseelement(self, multiparams, params)
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 817, in _execute_clauseelement compiled_sql, distilled_params
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 947, in _execute_context context)
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1108, in _handle_dbapi_exception exc_info
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 185, in raise_from_cause reraise(type(exception), exception, tb=exc_tb)
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 940, in _execute_context context)
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 435, in do_execute cursor.execute(statement, parameters)
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/newrelic-2.46.0.37/newrelic/hooks/database_dbapi2.py", line 22, in execute *args, **kwargs)
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute self.errorhandler(self, exc, value)
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler raise errorclass, errorvalue
ProgrammingError: (ProgrammingError) (1146, "Table 'relengapi.badpenny_job_logs' doesn't exist") 'SELECT badpenny_job_logs.id AS badpenny_job_logs_id, badpenny_job_logs.content AS badpenny_job_logs_content \nFROM badpenny_job_logs \nWHERE badpenny_job_logs.id = %s \n LIMIT %s' (2, 1)
```

**Comment by Callek** [comment]
correction current prod is 1.1.1

**Comment by djmitche** [comment]
Odd -- the table is, indeed, missing.  Yet there's a `badpenny_jobs_test` table with the same schema as `badpenny_jobs`.  This will get fixed during the 2.0.0 deploy.

**Comment by Callek** [comment]
fwiw badpenny_jobs_test was me forgetting to delete a table when I was done (I created it with the same schema and populated it) and then was trying to test issue #202 in our production DB, but failed miserably to even replicate it via a mysql session.

**Comment by djmitche** [comment]
Ah, ok.  FWIW this bug was from logged warnings I saw on my dev system, not in prod.
