### ISSUE TITLE
Badpenny tasks getting "MySQL server has gone away" errors.

### ISSUE THREAD

**Issue by djmitche** [mozilla/build-relengapi#214]
The tooltool replication task is getting these errors on every run starting yesterday at 5pm.  Yet the task still claims to have completed "instantly".  Also, the celery worker processes have restarted since then.

**Comment by djmitche** [comment]
"instantly" is incorrect (#215) - the job took about 8 minutes and 44 seconds.

**Comment by djmitche** [comment]
There are two issues here.

First, we should be using shorter-lived sessions, rather than holding the sessions open during the copy operation.

Second, we really shouldn't be caching sessions within a thread or a celery task.  Every call to `ap.db.session(dbname)` should return a new session.

**Comment by djmitche** [comment]
http://docs.sqlalchemy.org/en/latest/orm/session_basics.html#session-faq-whentocreate recommends a session per request -- which is what we're implementing now (and per celery task).  It also distinguishes "transaction scope" from "session scope", the former being shorter.  It's not clear how that interacts with disappearing DB connections, though.  A connection that goes away *during* a connection will definitely be a problem (I assume the MySQL rolls back any such transaction).  So it comes down to when sqlalchemy checks out a new connection from the pool (since that's when it pings and reconnects).

**Comment by djmitche** [comment]
fwiw, we have wait_timeout tuned *way* down here:
```
mysql> select @@global.wait_timeout;
+-----------------------+
| @@global.wait_timeout |
+-----------------------+
|                   600 |
+-----------------------+
1 row in set (0.00 sec)
```
that doesn't explain a failure in a 9-minute task, but hey, close enough.

**Comment by djmitche** [comment]
#217 is useful in testing this out.

**Comment by djmitche** [comment]
I set my local MySQL server to time out after 10s, and tested things out.  I added a 'print checkout' to the pool checkout listener, so we can see when a new connection is checked out (and thus validated to be still connected):
```
>>> s.execute('select 1')
checkout
<sqlalchemy.engine.result.ResultProxy object at 0x7f8044b0a6d0>
>>> s.execute('select 1')
<sqlalchemy.engine.result.ResultProxy object at 0x7f80453ebf50>
>>> s.execute('select 1')
<sqlalchemy.engine.result.ResultProxy object at 0x7f8044b0a7d0>
>>> s.execute('select 1')
<sqlalchemy.engine.result.ResultProxy object at 0x7f8044b0a850>
>>> s.execute('select 1')
<sqlalchemy.engine.result.ResultProxy object at 0x7f8044b0a8d0>
>>> import time
>>> time.sleep(10)
>>> s.execute('select 1')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/dustin/code/relengapi/t/relengapi/sandbox/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/dustin/code/relengapi/t/relengapi/sandbox/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1021, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/home/dustin/code/relengapi/t/relengapi/sandbox/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 841, in execute
    return meth(self, multiparams, params)
  File "/home/dustin/code/relengapi/t/relengapi/sandbox/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/dustin/code/relengapi/t/relengapi/sandbox/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 938, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/dustin/code/relengapi/t/relengapi/sandbox/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1070, in _execute_context
    context)
  File "/home/dustin/code/relengapi/t/relengapi/sandbox/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1271, in _handle_dbapi_exception
    exc_info
  File "/home/dustin/code/relengapi/t/relengapi/sandbox/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/dustin/code/relengapi/t/relengapi/sandbox/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1063, in _execute_context
    context)
  File "/home/dustin/code/relengapi/t/relengapi/sandbox/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
  File "/home/dustin/code/relengapi/t/relengapi/sandbox/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/dustin/code/relengapi/t/relengapi/sandbox/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (OperationalError) (2013, 'Lost connection to MySQL server during query') 'select 1' ()
>>> s.rollback()
>>> s.execute('select 1')
checkout
<sqlalchemy.engine.result.ResultProxy object at 0x7f8044b0abd0>
>>> s.commit()
>>> s.execute('select 1')
checkout
<sqlalchemy.engine.result.ResultProxy object at 0x7f8044b0add0>
>>> s.commit()
>>> time.sleep(10)
>>> s.execute('select 1')
checkout
checkout
<sqlalchemy.engine.result.ResultProxy object at 0x7f8044b17050>
```
In other words, after a commit, the session drops its hold on the connection, and checks it out again when the next transaction begins.

So the RelengAPI bits are correct here; it's a tooltool bug to try to hold a transaction open for so long.
