### ISSUE TITLE
MySQL doesn't like "UTC"

### ISSUE THREAD

**Issue by djmitche** [mozilla/build-relengapi#229]
In #31 we added the ability to set the per-connection timezone.  Worked on my local system, but not on MySQL:
```
OperationalError: (_mysql_exceptions.OperationalError) (1298, "Unknown or incorrect time zone: 'UTC'")
```

**Comment by djmitche** [comment]
```
11:21:19 <sheeri> So I would use utc_timestamp() to get the values, and store them in datetimes.
11:21:38 <sheeri> the value of the server's timezone does not affect the UTC_TIMESTAMP() function
11:21:51 <sheeri> but it does affect CURRENT_TIMESTAMP() and NOW()
```

so I think, for now, we should back out the "set time_zone" change, and separately make efforts to avoid timezone-sensitive functions and columns.

**Comment by djmitche** [comment]
Also, per http://technocation.org/files/doc/2009_12_timezones.pdf only TIMESTAMP columns are sensitive to the server-side timezone, so if we don't use that column type then we don't have to worry about this.

**Comment by djmitche** [comment]
Also, in trying to insert new data from treestatus:
`[Fri Aug 28 12:51:08 2015] [error] OperationalError: (_mysql_exceptions.OperationalError) (1292, "Incorrect datetime value: '2015-08-28 19:51:08.081088+00:00' for column 'when' at row 1") [SQL: u'INSERT INTO treestatus_log (tree, `when`, who, status, reason, tags) VALUES (%s, %s, %s, %s, %s, %s)'] [parameters: (u'tree10', datetime.datetime(2015, 8, 28, 19, 51, 8, 81088, tzinfo=<UTC>), 'human:dmitchell@mozilla.com', u'open', u'', '["backlog"]')]`

**Comment by djmitche** [comment]
Again, this is working fine on my system.  I wonder if [bug 1199301](https://bugzilla.mozilla.org/show_bug.cgi?id=1199301) (upgrade mysql client to 5.6) will help?

I've verified with a general query log that a 5.6 client + 5.6 server successfully send and receive timestamps with `+00:00` at the end.  I don't know why a 5.1 client would generate such a timestamp and then *itself* choke on it, but that seems to be what's happening.

**Comment by djmitche** [comment]
If not it will probably tip me over to using postgres fro RelengAPI.  MySQL is just such crap :(

**Comment by djmitche** [comment]
The other question here is, we've got other code inserting timestamps -- why does *this* query fail?

**Comment by djmitche** [comment]
It appears that the format error is actually coming from the server, rather than from the client's formatting code:
```
>>> e.execute('insert into treestatus_log (tags, reason, status, who, tree, `when`) values ("[]", "cuz", "half-open", "dustin", "treea", "2015-08-28 19:51:08.081088+00:00")')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1986, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 906, in execute
    return self._execute_text(object, multiparams, params)
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1054, in _execute_text
    statement, parameters
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1339, in _handle_dbapi_exception
    exc_info
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (_mysql_exceptions.OperationalError) (1292, "Incorrect datetime value: '2015-08-28 19:51:08.081088+00:00' for column 'when' at row 1") [SQL: 'insert into treestatus_log (tags, reason, status, who, tree, `when`) values ("[]", "cuz", "half-open", "dustin", "treea", "2015-08-28 19:51:08.081088+00:00")']
```

I wonder if it's the decimals, rather than the TZ?

**Comment by djmitche** [comment]
Nope:
`OperationalError: (_mysql_exceptions.OperationalError) (1292, "Incorrect datetime value: '2015-08-28 19:51:08+00:00' for column 'when' at row 1") [SQL: 'insert into treestatus_log (tags, reason, status, who, tree, `when`) values ("[]", "cuz", "half-open", "dustin", "treea", "2015-08-28 19:51:08+00:00")']`

**Comment by djmitche** [comment]
OK, that's silly.  The fix is to use @callek's UTCDateTime.

**Comment by djmitche** [comment]
..so there's nothing to fix here.  We don't ever let MySQL near timezones, so it doesn't matter what it thinks.
