### ISSUE TITLE
ISE on failed upload due to missing permissions

### ISSUE THREAD

**Issue by djmitche** [mozilla/build-relengapi#242]
_From @djmitche on May 19, 2015 16:54_

Via newrelic:
```
Traceback (most recent call last):
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request rv = self.dispatch_request()
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args)
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/newrelic-2.46.0.37/newrelic/hooks/framework_flask.py", line 40, in _nr_wrapper_handler_ return wrapped(*args, **kwargs)
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/relengapi/lib/api.py", line 103, in replacement result = wrapped(*args, **kwargs)
File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/relengapi/blueprints/tooltool/__init__.py", line 140, in upload_batch if not p.get('tooltool.upload.{}'.format(v)).can():
AttributeError: 'NoneType' object has no attribute 'can'
```

_Copied from original issue: mozilla/build-tooltool#21_

**Comment by djmitche** [comment]
Fixed in #287
