### ISSUE TITLE
Setting up on ubuntu needs additional python packages

### ISSUE THREAD

**Issue by Callek** [mozilla/build-relengapi#337]
So, I tried running validate.sh from a fresh install/virtualenv. This is ubuntu 15.04 just now.

After having to install things for python-ldap (-dev libraries to build it) I tried running validate with no changes, failed on "anyjson>=0.3.3" and on "amqp<2.0,>=1.4.5" and then:
```
======================================================================
ERROR: Failure: ImportError (No module named httpretty)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/callek/mozilla/obj/relengapi/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/callek/mozilla/obj/relengapi/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/callek/mozilla/obj/relengapi/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/callek/mozilla/git/build-relengapi/relengapi/blueprints/archiver/test_archiver.py", line 7, in <module>
    import moto
  File "/home/callek/mozilla/obj/relengapi/local/lib/python2.7/site-packages/moto/__init__.py", line 8, in <module>
    from .autoscaling import mock_autoscaling  # flake8: noqa
  File "/home/callek/mozilla/obj/relengapi/local/lib/python2.7/site-packages/moto/autoscaling/__init__.py", line 2, in <module>
    from .models import autoscaling_backends
  File "/home/callek/mozilla/obj/relengapi/local/lib/python2.7/site-packages/moto/autoscaling/models.py", line 3, in <module>
    from moto.core import BaseBackend
  File "/home/callek/mozilla/obj/relengapi/local/lib/python2.7/site-packages/moto/core/__init__.py", line 2, in <module>
    from .models import BaseBackend  # flake8: noqa
  File "/home/callek/mozilla/obj/relengapi/local/lib/python2.7/site-packages/moto/core/models.py", line 7, in <module>
    from httpretty import HTTPretty
ImportError: No module named httpretty
```

Is this just a failure of Ubuntu+my virtualenv version? or Some other issue?  (I'll expiriment more later, but wanted to get this on file now)

Pip Freeze:

```
(relengapi)callek@Centaurus:~/mozilla/obj/relengapi/src$ pip freeze
Babel==2.0
Flask==0.10.1
Flask-BrowserID==0.0.4
Flask-Login==0.2.11
IPy==0.83
Jinja2==2.8
Mako==1.0.2
MarkupSafe==0.23
Pygments==2.0.2
SQLAlchemy==1.0.8
Sphinx==1.3.1
WSME==0.7.0
WebOb==1.4.1
Werkzeug==0.10.4
alabaster==0.7.6
alembic==0.8.2
amqp==1.4.6
anyjson==0.3.3
argparse==1.2.1
billiard==3.3.0.20
blinker==1.4
boto==2.38.0
bzrest==0.9
celery==3.1.18
coverage==3.7.1
croniter==0.3.8
docutils==0.12
elasticache-auto-discovery==0.0.5
funcparserlib==0.3.6
funcsigs==0.4
furl==0.4.8
futures==3.0.3
itsdangerous==0.24
kombu==3.0.26
mock==1.3.0
mockcache==1.0.1
mockldap==0.2.5
moto==0.4.12
mozdef-client==1.0.4
netaddr==0.7.18
nose==1.3.7
orderedmultidict==0.7.5
pbr==1.6.0
pep8==1.6.2
pyflakes==0.9.2
python-dateutil==2.4.2
python-editor==0.4
python-ldap==2.4.20
python-memcached==1.57
pytz==2015.4
redo==1.5
-e git+ssh://github.com/mozilla/build-relengapi@a9981a9d7647b627b809c8e73525bd183b382638#egg=relengapi-master
requests==2.7.0
requests-futures==0.9.5
simplegeneric==0.8.1
simplejson==3.8.0
six==1.9.0
snowballstemmer==1.2.0
sphinx-rtd-theme==0.1.8
structlog==15.2.0
wrapt==1.10.5
wsgiref==0.1.2
```

**Comment by Callek** [comment]
OOOooook, this was just a fault of the -dev packages missing I suspect, a newly generated virtualenv + pip install -e worked "just fine"
